CREATE TABLE MyTable
(
    id  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    val NUMBER NOT NULL,
    CONSTRAINT id_unq UNIQUE (id)
);

BEGIN
    FOR i IN 1..10000
        LOOP
            INSERT INTO MyTable (val) VALUES (DBMS_RANDOM.RANDOM);
        end loop;
end;

