--------------------------------------------------------
--  DDL for Sequence GROUPS_LOGS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "GROUPS_LOGS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence GROUPS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "GROUPS_SEQ" MINVALUE 1 MAXVALUE 1000000 INCREMENT BY 1 START WITH 9 CACHE 2 NOORDER CYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence GROUPS_SEQ1
--------------------------------------------------------

CREATE SEQUENCE "GROUPS_SEQ1" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence GROUPS_SEQ2
--------------------------------------------------------

CREATE SEQUENCE "GROUPS_SEQ2" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence MYTABLE_LOGS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "MYTABLE_LOGS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 581681 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence MYTABLE_SEQ
--------------------------------------------------------

CREATE SEQUENCE "MYTABLE_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20021 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence MYTABLE_SEQ1
--------------------------------------------------------

CREATE SEQUENCE "MYTABLE_SEQ1" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_LOGS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_LOGS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 608241 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_LOGS_SEQ1
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_LOGS_SEQ1" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_SEQ
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_SEQ1
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_SEQ1" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_SEQ2
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_SEQ2" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Sequence STUDENTS_SEQ3
--------------------------------------------------------

CREATE SEQUENCE "STUDENTS_SEQ3" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--------------------------------------------------------
--  DDL for Table GROUPS
--------------------------------------------------------

CREATE TABLE "GROUPS"
(
    "ID"    NUMBER,
    "NAME"  VARCHAR2(200 BYTE),
    "C_VAL" NUMBER
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table GROUPS_LOGS
--------------------------------------------------------

CREATE TABLE "GROUPS_LOGS"
(
    "ID"         NUMBER,
    "OPERATION"  VARCHAR2(200 BYTE),
    "RECORDEDON" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    "OLDID"      NUMBER,
    "OLDNAME"    VARCHAR2(200 BYTE),
    "OLD_C_VAL"  NUMBER,
    "NEWID"      NUMBER,
    "NEWNAME"    VARCHAR2(200 BYTE),
    "NEW_C_VAL"  NUMBER
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table MYTABLE
--------------------------------------------------------

CREATE TABLE "MYTABLE"
(
    "ID"   NUMBER,
    "VAL"  NUMBER,
    "NAME" VARCHAR2(200 BYTE)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table MYTABLE_LOGS
--------------------------------------------------------

CREATE TABLE "MYTABLE_LOGS"
(
    "ID"         NUMBER,
    "OPERATION"  VARCHAR2(200 BYTE),
    "RECORDEDON" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    "OLDID"      NUMBER,
    "OLDVAL"     NUMBER,
    "OLDNAME"    VARCHAR2(200 BYTE),
    "NEWID"      NUMBER,
    "NEWVAL"     NUMBER,
    "NEWNAME"    VARCHAR2(200 BYTE)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

CREATE TABLE "STUDENTS"
(
    "ID"        NUMBER,
    "NAME"      VARCHAR2(200 BYTE),
    "GROUP_ID"  NUMBER,
    "DATE_TIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table STUDENTS_LOGS
--------------------------------------------------------

CREATE TABLE "STUDENTS_LOGS"
(
    "ID"         NUMBER,
    "OPERATION"  VARCHAR2(20 BYTE),
    "RECORDEDON" TIMESTAMP(6) DEFAULT SysTimeStamp,
    "OLDID"      NUMBER,
    "OLDNAME"    VARCHAR2(200 BYTE),
    "OLDGROUPID" NUMBER,
    "NEWID"      NUMBER,
    "NEWNAME"    VARCHAR2(200 BYTE),
    "NEWGROUPID" NUMBER,
    "OLDTIME"    TIMESTAMP(6),
    "NEWTIME"    TIMESTAMP(6)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table T1
--------------------------------------------------------
CREATE TABLE "T1"
(
    "C1" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE,
    "C2" VARCHAR2(10 BYTE)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
    TABLESPACE "USERS";